import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const routes = [
  { text: 'data cache basic', pathname: '/' },
  {
    text: 'with route segment',
    pathname: '/with-route-segment',
  },
  { text: 'with fetch', pathname: '/with-fetch' },
  { text: 'with dynamic', pathname: '/with-dynamic' },
  { text: 'with dynamic-2', pathname: '/with-dynamic-2' },
  { text: 'with dynamic-3', pathname: '/with-dynamic-3' },
];
export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div className="container mx-auto px-12">
          <div className="flex font-bold text-6xl justify-center py-10">
            How is Next.js cache working?
          </div>
          <div className="flex gap-x-14">
            <div className="space-y-4 shrink-0">
              {routes.map((route) => (
                <div key={route.text}>
                  <Link
                    href={route.pathname}
                    className="font-semibold text-blue-500 hover:underline hover:text-blue-500/90"
                  >
                    {route.text}
                  </Link>
                </div>
              ))}
            </div>
            <main className="space-y-6 grow">{props.children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
